### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by timja** [jenkinsci/lib-access-modifier#31]
I've added it to ci.jenkins.io, just needs a Jenkinsfile

**Comment by jglick** [comment]
BTW the problem as I see it is that https://ci.jenkins.io/job/Plugins/ matches `*-plugin` while there are other subfolders for other sorts of components, yet the config is all the same—just looking for a `Jenkinsfile`. Would be simpler IMO to just have one org folder, so that component repo owners could autonomously activate CI.

**Comment by timja** [comment]
> BTW the problem as I see it is that [ci.jenkins.io/job/Plugins](https://ci.jenkins.io/job/Plugins/) matches `*-plugin` while there are other subfolders for other sorts of components, yet the config is all the same—just looking for a `Jenkinsfile`. Would be simpler IMO to just have one org folder, so that component repo owners could autonomously activate CI.

We could probably change that although it would likely end up breaking a whole bunch of links and badges unless we kept the folder called Plugins.

cc @oleg-nenashev

**Comment by jglick** [comment]
True that `Plugins` has to stay for compatibility. Maybe the other folders could be merged into one matching everything that is _not_ `*-plugin`? That would still break a few links but I hope a manageable number.

**Comment by oleg-nenashev** [comment]
We do not add new libraries too often, and it is not a big overhead to add a new project to CI.

**Comment by oleg-nenashev** [comment]
@timja @jglick note that many libraries use the `lib-foobar` naming pattern. We could probably change it to `foobar-lib` for new components and add filters

**Comment by timja** [comment]
Previous config:
`(lib-version-number|groovy-sandbox|xstream-fork|config-provider-model|dom4j|jelly|lib-jenkins-maven-artifact-manager|lib-jenkins-maven-embedder|lib-jira-api|libzfs4j|maven-interceptors|lib-task-reactor|plugin-compat-tester|extras-executable-war|lib-crypto-util|xtrigger-lib|trilead-ssh2|access-modifier)`

New config:
`(lib-.*|.*-lib|groovy-sandbox|config-provider-model|dom4j|jelly|libzfs4j|maven-interceptors|plugin-compat-tester|extras-executable-war|lib-crypto-util|trilead-ssh2|access-modifier)`

should we rename this to prefix with lib?

**Comment by oleg-nenashev** [comment]
`lib-.*` is safe, no collisions with plugins

**Comment by timja** [comment]
access-modifier-lib

or

lib-access-modifier?

**Comment by oleg-nenashev** [comment]
No strong opinion. `lib-access-modifier` is current pattern, but the second option looks better

**Comment by timja** [comment]
let's be consistent
